puts "Seeding Items..."

DailyItem.create(name: "Octane", cost: 700, rarity: "Import Body", color: "Saffron", date: Time.new, image: "https://i.imgur.com/O3vNJRN.png")
DailyItem.create(name: "Hexed", cost: 2000, rarity: "Black Market Decal", color: "Default", date: Time.new, image: "https://i.imgur.com/DgVyPA5.png")
DailyItem.create(name: "Infinium", cost: 700, rarity: "Exotic Wheels", color: "Default", date: Time.new, image: "https://i.imgur.com/7dwrPiy.png")
DailyItem.create(name: "Storm Watch", cost: 2000, rarity: "Black Market Decal", color: "Default", date: Time.new, image: "https://i.imgur.com/O3vNJRN.png")
DailyItem.create(name: "Quimby", cost: 200, rarity: "Very Rare Wheels", color: "Default", date: Time.new, image: "https://i.imgur.com/DgVyPA5.png")
DailyItem.create(name: "Xenosplash", cost: 200, rarity: "Very Rare Rocket Boost", color: "Default", date: Time.new, image: "https://i.imgur.com/7dwrPiy.png")
DailyItem.create(name: "Tailwind: Schematized", cost: 600, rarity: "Import Wheels", color: "Black", date: Time.new, image: "https://i.imgur.com/O3vNJRN.png")
DailyItem.create(name: "Neoctane", cost: 100, rarity: "Rare Banner", color: "Default", date: Time.new, image: "https://i.imgur.com/DgVyPA5.png")
DailyItem.create(name: "Canister", rarity: "Rare", Type: "Wheel", Color: "", Image: "https://rl.insider.gg/en/pc/wheels/canister")
DailyItem.create(name: "Hasher", rarity: "Very Rare", Type: "Wheel", Color: "", Image: "https://rl.insider.gg/en/pc/wheels/hasher")
DailyItem.create(name: "Hasher: SE", rarity: "Very Rare", Type: "Wheel", Color: "", Image: "https://rl.insider.gg/en/pc/wheels/hasher/inverted")
DailyItem.create(name: "Jak'd", rarity: "Very Rare", Type: "Wheel", Color: "", Image: "https://rl.insider.gg/en/pc/wheels/jak_d")
DailyItem.create(name: "Jak'd: Obverse", rarity: "Exotic", Type: "Wheel", Color: "", Image: "https://rl.insider.gg/en/pc/wheels/jak_d/obverse")
DailyItem.create(name: "Chakram: Holographic", rarity: "Import", Type: "Wheel", Color: "", Image: "https://rl.insider.gg/en/pc/wheels/chakram/holographic")
